### PR TITLE
Add ability to select whole group

### PR DESCRIPTION
**Pull request by kubacode**
This PR adds the optional ability to select all options in a group. If all options are already selected, then all options will be deselected.

### CODE REVIEW

**Comment by shentao** [comment]
This looks very promising. Planning to do some work on multiselect tomorrow. Will merge it then. Thanks for the contribution. I’m sorry that I’m so laggy lately (VueConf takes all my free time)

**Comment by prodiger** [comment]
How's the progress? Would love to see this feature.

**Comment by mekonnenjr** [comment]
What is the state of this PR?

**Comment by mekonnenjr** [comment]
What is the status of this PR?

**Comment by sourenaraya** [comment]
This would be very useful.

**Comment by vms82** [comment]
Any news about this really usefull enhancement?

**Comment by shentao** [comment]
I know it’s late but I feel I neglected the duty for too long already... Sorry about that. To those who still care about this change it’s merged to master (https://github.com/shentao/vue-multiselect/commit/eca59ac2da46ba9486ea9cb48c02738d0de9dc2f).

Had to make some changes to the code though. Thanks @kubacode!

**Pull request closed without merging**
