### PR TITLE
Add input-class option

### PR DESCRIPTION
**Pull request by Toilal**
This option may be useful when using this component in CSS frameworks that requires to add a CSS class on form input. (ie: `form-control` on bootstrap 3).

### CODE REVIEW

**Comment by theromie** [comment]
How to give custom class name?

**Comment by Toilal** [comment]
`<vue-multiselect input-class="some-class" ...>`

**Comment by theromie** [comment]
<multiselect :options="options" label="sports_name" :custom-label="sportName" select-label="" selected-label="" deselect-label="" input-class="sports_select"></multiselect >
giving me  Cannot read property 'tagName' of null

**Comment by Toilal** [comment]
You may try my fork https://github.com/Toilal/vue-multiselect, it includes this pull request.

**Comment by theromie** [comment]
Its added class to <div tabindex="0" class="multiselect" input-class="sports_select"></div> not to input

**Comment by Toilal** [comment]
Format your markdown, I can't read it.

**Comment by Toilal** [comment]
Any chance to get this merge if I rebase it ? @shentao

**Comment by shentao** [comment]
Not sure if this matters any longer, but sorry for the delay..

**Pull request merged**
