### PR TITLE
Add `required` prop

### PR DESCRIPTION
**Pull request by Shamus03**
Ability to set the `required` attribute on the HTML input element.  This is useful when using modern browsers' builtin form validation.

### CODE REVIEW

**Review by wasiqwiqar — APPROVED** [review]
Pretty straightforward and simple, was just looking for this in my current project

**Review by ZS-Andisch — APPROVED** [review]
Simple and important change

**Comment by akki-jat** [comment]
@Shamus03 Please resolve the merge conflict.

**Comment by akki-jat** [comment]
@mattelen We can add this simple improvement now as we have released the v3.

**Comment by Shamus03** [comment]
> @Shamus03 Please resolve the merge conflict.

Done!

**Review by akki-jat — APPROVED** [review]

**Pull request merged**
