### PR TITLE
fix: disabled grouped options get extra multiselect__option--group class

### PR DESCRIPTION
**Pull request by akki-jat**
for more info #1081

### CODE REVIEW

**Comment by shentao** [comment]
Thank you for the PR!

**Comment by shentao** [comment]
Nevermind the above "revert". Pressed on accident, the change was not reverted.

**Comment by kaidjohnson** [comment]
In the latest release (2.1.6) from npm, it appears that this PR was reverted, or else the release cut was done before March 9.

I'm still seeing this code from npm:

```
    groupHighlight (index, selectedGroup) {
      if (!this.groupSelect) {
        return ['multiselect__option--group', 'multiselect__option--disabled']
      }
```

**Comment by akki-jat** [comment]
@kaidjohnson - this is not released yet.

**Comment by aazhuravlev** [comment]
@akki-jat could you tell please when will be release to solve the problem?

**Comment by akki-jat** [comment]
@shentao - can you deploy this change in patch release?

**Comment by shentao** [comment]
@akki-jat I wish I could, but the master branch is entirely broken for me. The setup requires some work... Until that’s resolved I don’t have the confidence to release anything on 2.x.

**Comment by destradafilm** [comment]
@shentao Thanks for your work on this. Any updates on merging this branch? thanks!

**Comment by destradafilm** [comment]
I'm tempted to just branch off the latest release and fix this locally or just look for another library 😞

**Comment by shentao** [comment]
Both options sound good to me. 👍

**Pull request merged**
