### PR TITLE
Fix tabbing issues

### LINKED ISSUE #685: Tabbing does not work to searchable multiselects
The recent "Improve the `singleLabel` slot feature" commit - [Multiselect.vue line 35](https://github.com/shentao/vue-multiselect/commit/13f7fb6617e580443543996f0e0d8c4467d25652#diff-f0fe4bcbb4c9df5319d483db4c27ee58R35) introduces a regression for issues #411 , #515 and similar. With this shift-tabbing and even tabbing to searchable multiselects does not work anymore.

This is because `v-show` on `<input` sets `style="display: none"` on the DOM element. Such elements ignore tabindex in the browser.

In earlier commits "[Set tabindex on input instead of container if searchable](https://github.com/shentao/vue-multiselect/commit/3e963b21b75e76894b6d72ce12832668cbb98eb2#diff-f0fe4bcbb4c9df5319d483db4c27ee58L254)"  I can see that there have been attempts to avoid "display: none".

I've made this fiddle to reproduce it. Pushing Tab on the keyboard from first input should jump to multiselect. This is working with 2.0.8 libs, but not 2.1.0 libs:

https://jsfiddle.net/rjr8n2oc/1/

### PR DESCRIPTION
**Pull request by sigerello**
Fix #685, #411, #515

### CODE REVIEW

**Comment by cvn** [comment]
Hey @sigerello I tested your `fix-tabbing` branch for vue-multiselect, and I don't see much difference between it and the [latest master](https://github.com/shentao/vue-multiselect/tree/17532b02ad73f7bc5f8dbd896d98b79c1e4b6493) from @shentao. Tab behavior seems to work well with both. I'm testing with Chrome. Is there anything I'm missing?

**Comment by sigerello** [comment]
This PR consists of two commits: [this one](https://github.com/shentao/vue-multiselect/pull/804/commits/2755517ebe7a2368a0caf26324424f68a126facd) is actually a fix, and [second one](https://github.com/shentao/vue-multiselect/pull/804/commits/f0184b1762f2351ef4fa4790a0d75fe9b4226be3) is not directly related to mentioned issues - it's just code style fixes.

Lets compare in detail 4 versions on JSFiddle:
1. [shentao/vue-multiselect/tree/v2.0.3](https://jsfiddle.net/sigerello/qc2ejph0/5/)
2. [shentao/vue-multiselect/tree/v2.1.0](https://jsfiddle.net/sigerello/s2h74ywe/18/)
3. [shentao/vue-multiselect/master](https://jsfiddle.net/sigerello/73wc2jup/124/)
4. [sigerello/vue-multiselect/fix-tabbing](https://jsfiddle.net/sigerello/2xhz0jyL/6/)

Each of them has the same markup and scripts, the only difference is loaded version of vue-multiselect in "resources" section.

We have 3 multiselect instances here:
1. single select, searchable=true
2. multiple select, searchable=true
3. multiple select, searchable=false

Test scenario is the same for each version:
1. Click on top link and then click tab to move focus to multiselect instance.
2. When vue-multiselect instance gets focus, click down key (one or several times - just to change highlighted item in list to another one item).
3. Click tab again to move focus to next multiselect instance.
4. Repeat steps 2,3 until bottom link gets focus.
5. Now go in reverse order by clicking shift+tab and repeating step 2.

Results for each version:

[shentao/vue-multiselect/tree/v2.0.3](https://jsfiddle.net/sigerello/qc2ejph0/5/):
- We successfully went down to bottom link.
- Clicking Tab and Shift+Tab doesn't select item on searchable instances, but does select one if instance is "no searchable". This is a bug.
- When we go in reverse order, we can reach searchable instance, but clicking Shift+Tab on it - doesn't work, so we can't go upper and stuck here. This is a bug.

[shentao/vue-multiselect/tree/v2.1.0](https://jsfiddle.net/sigerello/s2h74ywe/18/):
- We can't focus searchable instances at all by tabbing, but can focus "no searchable" instance. This is a bug.
- Clicking Tab and Shift+Tab doesn't select item on searchable instances, but does select one if instance is "no searchable". This is the same bug as in v2.0.3.

[shentao/vue-multiselect/master](https://jsfiddle.net/sigerello/73wc2jup/124/):
- We can move down and up by tabbing on all instances (yay!)
- Clicking Tab and Shift+Tab doesn't select item on searchable instances, but does select one if instance is "no searchable". The same bug as in v2.0.3 and v2.1.0.

[sigerello/vue-multiselect/fix-tabbing](https://jsfiddle.net/sigerello/2xhz0jyL/6/):
- We can move down and up by tabbing on all instances (already fixed in shentao/master)
- Tabbing doesn't select items on any instances but just moving focus between them as it intended to be (finally!)

**Comment by cvn** [comment]
Hey @sigerello, thanks for the detailed explanation.

I'm not sure if everyone considers select on tab to be a bug. I say this because in #612 and #654, several people say they want select on tab for searchable multiselects. In [one comment](https://github.com/shentao/vue-multiselect/issues/612#issuecomment-419089072), @shentao implies this was his intention as well. I don't know how any of them would feel about select on tab in non-searchable multiselects.

**Comment by sigerello** [comment]
IMO, tabbing has nothing to do with selections. This leads to unexpected selections and poor user experience. Tabbing should only change focus between elements. We have Enter and Space buttons to make selections. All standard form elements behave this way.
But anyway, if it was intended to behave like that, I think it should be:
1. Configurable, so we can explicitly enable this feature if needed.
2. Consistent, so it should behave the same way for all instances - searchable ones and not searchable ones.

**Comment by shentao** [comment]
In this case I agree with @sigerello – I’m all for sticking to how a native select behaves. This means tabs should not trigger a select. This is also how it used to work. But then there were issues that we should make the tab key trigger the selection if the pointer is dirty. This also makes sense in some cases.

We should probably lean towards making it explicit by setting a prop flag. Another improvement that should make this issue less pressing will be to not open the dropdown on focus. Instead the user will need to click space/arrow/enter to open the dropdown. This behaviour is already present in the current v3.

**Comment by DinsmoreDesign** [comment]
> IMO, tabbing has nothing to do with selections. This leads to unexpected selections and poor user experience. Tabbing should only change focus between elements. We have Enter and Space buttons to make selections. All standard form elements behave this way.
> But anyway, if it was intended to behave like that, I think it should be:
> 
> 1. Configurable, so we can explicitly enable this feature if needed.
> 2. Consistent, so it should behave the same way for all instances - for searchable ones and not searchable ones.

I feel like this should be configurable in some way (I haven't found anything in the docs, if there is a way?). @shentao - I definitely don't agree that we should have to press enter - a normal <select> menu allows you to move through the options with the keyboard and tabbing keeps your suggestion. Vue-Multiselect requires you to press enter to select, instead. This is _not_ good User Experience, because it functions differently from the standard HTML functionality...

**Pull request closed without merging**
