### PR TITLE
Added support for show no tags

### PR DESCRIPTION
**Pull request by akki-jat**
Implementation of feature as described in #750

### CODE REVIEW

**Comment by akki-jat** [comment]
No @VCodepp.
It can be used after library owner merge the commit and release the updated version.

**Comment by warbio** [comment]
Hope this get merged soon 👍

**Comment by VCodepp** [comment]
Name can be like this; 

visibleTag="true" 

or 

selectedMode="tag"/"count"

**Comment by akki-jat** [comment]
@shentao what do you suggest?
I first thought of **hideTag**.
Or **showSelectionCount** will be good choice.

Or if you have anything special in mind, tell me.

**Comment by shentao** [comment]
I’ve been thinking some more about this and I wonder if we could provide such a feature by actually implementing a slot around the selected values (tags) so that someone can provide their own template and implementation of selected elements (also in a form of `5 options selected`) rather than by using another prop. This should provide much more flexibility while also cutting the API surface and making it easier to maintain (which is hard nowadays :( )

**Comment by akki-jat** [comment]
Hi @shentao, were you talking about something like this (f5ad5af) ?

**Comment by VCodepp** [comment]
is there still no improvement?

**Comment by VCodepp** [comment]
is there still no improvement?

**Comment by akki-jat** [comment]
@shentao any response?
I want to use this feature. So can you make it fast.
And I am sure many more are waiting for this feature?

**Comment by sra** [comment]
Can this be used to eliminate the tags completely? In our case the selected items are displayed elsewhere.

**Comment by akki-jat** [comment]
@sra Yup, you can do whatever you want.

**Comment by akki-jat** [comment]
@shentao any response?

**Comment by shentao** [comment]
Finally merged with some additional improvements. Should be released today... 
Apologies for taking so long.

**Comment by shentao** [comment]
Released in 2.1.2 😅

**Pull request merged**
