### PR TITLE
Add slot that shows message about empty options

### PR DESCRIPTION
**Pull request by a-ryazanov**
Add slot that shows message about empty options.
Relates to #698.

### CODE REVIEW

**Comment by shentao** [comment]
Thanks! :)

**Comment by bakaat** [comment]
Lads the js dist file doesn't contain the change :o

**Comment by janswist** [comment]
It might be a good idea to add info about `noOptions` slot to documentation so others won't have to dive in into actual code to find this :)

**Comment by shentao** [comment]
Would you like to provide a PR with that information? Just the source files, no need to build.

**Comment by janswist** [comment]
Never done PR before and don't want to mess what's already made...

**Comment by piotrorlowski** [comment]
@shentao Once there was an issue https://github.com/shentao/vue-multiselect/issues/39

Is it still possible somehow to not show List is empty if there is no query? 

For example when user clicks/focuses on multiselect input but doesn't type anything?

Empty span with `slot="noOptions"` doesn't do the job, because it shows simply empty dropdown's option.

I would require to not show anything underneath multiselect (i.e. not any option) if there is nothing typed into an input and I don't want to solve this by adding class and styling it with `display: none;`.

Any idea how to do this?

**Comment by shentao** [comment]
I imagine this can be done with CSS by putting `display: none` to the class on that element.

**Comment by piotrorlowski** [comment]
@shentao 

You would have to put `display: none` on `.multiselect__content-wrapper` and add dependency when there is an empty-query.

However I wondered if there's some simpler, prettier solution, like some option in your component.

**Comment by Ashu-r** [comment]
@piotrorlowski Thanks for workaround.
In case someone needs explaination:
```
<style>
.input_empty .multiselect__content {
  display: none !important;
}
</style>
```
```
<multiselect
        .....
        :class="{ input_empty: isInputEmpty }"
        @search-change="inputChange"
      >
```
```
inputChange(query) {
      if (query.length > 0 || this.inputs.length > 0) {
        this.isAddressesEmpty = false
      } else {
        this.isAddressesEmpty = true
      }
}
```
Something like this may work for you.

**Pull request merged**
