### PR TITLE
v3.0

### PR DESCRIPTION
**Pull request by shentao**

### CODE REVIEW

**Comment by Koc** [comment]
Would be nice add support of the virtual list in next major version https://github.com/tangbc/vue-virtual-scroll-list or https://github.com/Akryum/vue-virtual-scroller

limitting options is not the solution because it confuses users (why some cities are missing?)

**Comment by shentao** [comment]
Hey @Koc, this is something you will be able to add yourself thanks to the new, more flexible slots/API in the upcoming v3.0. I don’t want to add virtual scrolling since implementing that is a task for a standalone library (like Akryum's vue-virtual-scroller) and adding it to Multiselect would make the bundle much larger than it has to be.

**Comment by st-sloth** [comment]
@shentao, that is awesome news! Thank you! What's the ETA of v3.0?
Also, will v2.2 be released? There have been lots of useful changes since the last release.

**Comment by shentao** [comment]
Closing this since I don’t think the PR will ever be merged. At some point v3 will just replace master alltogether and the current master will become `v2`.

**Pull request closed without merging**
