### PR TITLE
fix: show list is empty #1636

### PR DESCRIPTION
**Pull request by milan-lakhani**
Now by default list is empty will be show on selecting all the options from the list

### CODE REVIEW

**Comment by milan-lakhani** [comment]
Current behavior: 
Screenshot from 2023-05-16 16-25-07

Resolved Issue Behavior: 
Screenshot from 2023-05-16 16-24-27

**Comment by mattelen** [comment]
Thanks for looking into this issue. We will only be releasing major show stopper bugs for V2, and instead focusing our attention to V3. Since this isn't a show stopper issue, I've reassigned your branch to our `next` branch, as we will be launching V3 from there. Can you fix up the Merge Conflicts, then I'll review it

**Comment by milan-lakhani** [comment]
Hey @mattelen , I am sorry to bother you. But I forked this repo and kept the "fork only main" chekbox to true. So, I was wondering how can I switch to the next branch and rebase. I am a bit new to the git. Could you please help me? Thanks!

**Comment by milan-lakhani** [comment]
Opening a new PR as the issue diverted to next branch from master

**Pull request closed without merging**
