### PR TITLE
Fix for removing correct selected Items if MultiSelect array allows for duplicates

### PR DESCRIPTION
**Pull request by dannynicolas**
See https://github.com/shentao/vue-multiselect/pull/614 for details. Credit to @Jtorrecilla for this fix. 

This is a branch with the code from PR- https://github.com/shentao/vue-multiselect/pull/614 that fixes issue https://github.com/shentao/vue-multiselect/issues/282, that hopefully can be easily merged in the next release. 

Happy to make any changes needed / requested.

### CODE REVIEW

**Comment by Jtorrecilla** [comment]
Thanks @dannynicolas , I didn't realized about your previous comment!

**Comment by Owlnofeathers** [comment]
Id like to see this merged in, would fix issue #282 for our team using this package

**Comment by NewkirkS** [comment]
I'd also like to have this fix. Experiencing issue #282 as well.

**Comment by shentao** [comment]
If you’re experiencing issue #282 it probably means you operate on an array of objects and forgot to pass the required `label` and `track-by` props.

Please read the docs: https://vue-multiselect.js.org/#sub-single-select-object

Not accepting this PR. Sorry.

**Pull request closed without merging**
