### PR TITLE
Version 3.0 Docs

### PR DESCRIPTION
**Pull request by mattelen**
I've migrated the docs from the old vue cli to the vite based Vue 3 app. I've also removed the pug language aspect of the docs.

This was a larger task than I thought it would be, and as a result, some of the approaches I've taken I now regret. Biggest one is how the example blurb and example code are in separate folders, and a bit confusing. 

In the future, I'd love to migrate the docs to a VitePress setup. I thought it would be to much to do as part of this, but it's taken me so long to get this point, maybe I should have just done it - but thats ok, something for next time.

I've also swapped out the previous code view tool to Shiki, as its what VitePress and Vue use.

In terms of a code review, there is a lot here. If you want to priorities, I would like a test of the docs in the browser - make sure examples work, but also that the example and the docs are actually correct. I've tried to catch all the this.value -> this.modelValue etc, but there might be one that I've missed. 
To run the docs, please run `npm run dev`

### CODE REVIEW

**Comment by mattelen** [comment]
@akki-jat when you have a moment, I would appreciate a look over the documentation, and make sure I haven't missed anything in terms of general vue 2 -> vue 3 changes, or any other mistakes I may have made. Feel free to look at the code, but as I've mentioned earlier, it isn't that great, but keen to get this out. I'll fix up the circleci issues in the meantime

**Review by akki-jat — APPROVED** [review]
@mattelen Checked locally, looks good to me. Good work.

**Comment by akki-jat** [comment]
> @akki-jat when you have a moment, I would appreciate a look over the documentation, and make sure I haven't missed anything in terms of general vue 2 -> vue 3 changes, or any other mistakes I may have made. Feel free to look at the code, but as I've mentioned earlier, it isn't that great, but keen to get this out. I'll fix up the circleci issues in the meantime

@mattelen I have fixed CircleCI issue. I think we can go ahead with this.

**Comment by mattelen** [comment]
> @mattelen I have fixed CircleCI issue with [1c8592a](https://github.com/shentao/vue-multiselect/commit/1c8592a4c27e9c39e5c42644591c747b053dbd99). I think we can go ahead with this.

Ah fantastic, thanks so much for this @akki-jat

**Pull request merged**
