### PR TITLE
Solve issue #937: Uncaught error on backspace.

### PR DESCRIPTION
**Pull request by phlegx**

### CODE REVIEW

**Comment by shentao** [comment]
I wonder how this could be like this for so long. Anyway, would you be able to add a test case for that? I will try to prepare a release this weekend.

Thanks a lot for the contribution!

**Comment by phlegx** [comment]
Hi @shentao! Why write a test?

`this.internalValue[this.internalValue.length - 1]` can only be made if `this.internalValue.length` is greater then zero. Array of index -1 is not possible anyway.

**Comment by jackkoppa** [comment]
Thanks @phlegx for the fix, looks awesome. Will watch for the release; we definitely see this a fair amount in our usage

**Comment by TiborMalmo** [comment]
Thank you for the fix! 

Is there any plans for when the next release is going to be live? 😄

**Comment by jessuni** [comment]
Hi @shentao! Any plans that this fix will be released soon? We've been getting the same error frequently.

**Comment by Rubemlrm** [comment]
Hi @shentao , first of all great work on vue-multiselect. There is any plan to release this PR  soon ?

**Comment by desaintflorent** [comment]
The 2.1.6 version has been released guys ! A couple of hours ago, and i can confirm the backspace bug is gone on my app.

**Pull request merged**
