### PR TITLE
New bundle to include 'autocomplete="off"' in the minified dist

### PR DESCRIPTION
**Pull request by MellowCobra**
In the source code, `autocomplete` has been correctly set to "off" but in the minified bundle it is still set to "nope".

Ran the bundle script to rebuild the minified distribution scripts to pull in your latest changes.

### CODE REVIEW

**Comment by shentao** [comment]
Hey. Thanks for the contribution, but PRs should only contribute the source code, not the compiled code.

**Comment by MellowCobra** [comment]
Gotcha. Thanks!

**Comment by kgrosvenor** [comment]
Has this been merged? Im stuck on this issue at the minute!

**Comment by michaelschofield** [comment]
> Has this been merged/compiled into a version? Im stuck on this issue at the minute!

Just echoing the same thing! Accessibility scanners are flagging this.

**Comment by mattelen** [comment]
Closing due to only having bundled code changed. We hope to publish a new version with the changes around this in the coming weeks

**Pull request closed without merging**
