### PR TITLE
Hide remove element button

### PR DESCRIPTION
**Pull request by SirLamer**
When clearing a selected option is not allowed but the 'remove' button is shown, it just doesn't work. This is very confusing for a user who doesn't understand what is going on. It looks like the function is broken. So, instead, let's just not show it!

### CODE REVIEW

**Comment by SirLamer** [comment]
I just added the same treatment to the deselect highlight in the options list.

**Comment by SirLamer** [comment]
Note this does NOT pass the unit testing. I will look in to it.

**Comment by SirLamer** [comment]
Okay, I had just merged a branch in the wrong direction. I merged my private "custom for my project" branch in to this PR branch, instead of the inverse as intended. All tests pass now.

**Comment by shentao** [comment]
Great! Will look through it during the weekend! Thanks a lot! 🔥

**Comment by SirLamer** [comment]
By the way, given my other PR regarding null values, that fix is not implemented in this PR and yet it passes. You might want to add a unit test for accepting 'null' in the 'value' prop, and another unit test for clearing the last remaining selection.

**Comment by shentao** [comment]
Good catch! :)

**Comment by SirLamer** [comment]
Conflicts have arisen as a result of other work on the project ongoing. If I affect this on the latest code instead, will it be considered quickly enough to then be merged in to the project?

**Comment by shentao** [comment]
This is no longer needed due to the `tag` slot.

**Pull request closed without merging**
