### PR TITLE
Added type definition file

### LINKED ISSUE #696: Typescript support
How can I make package work in typescript?

I am getting an error:

> Could not find a declaration file for module 'vue-multiselect'. '/node_modules/vue-multiselect/dist/vue-multiselect.min.js' implicitly has an 'any' type.
  Try `npm install @types/vue-multiselect` if it exists or add a new declaration (.d.ts) file containing `declare module 'vue-multiselect';`

### PR DESCRIPTION
**Pull request by akki-jat**
Resolves #696

### CODE REVIEW

**Comment by shentao** [comment]
Thanks!

**Comment by rajmondburgaj** [comment]
Hi @shentao, for some reason I still get the same error as mentioned in #696, when I try to install it using webstorm i get this error:

image

Do you have any idea what might be the problem?

This is the command for installation: `npm install vue-multiselect@next`

**Comment by akki-jat** [comment]
@rajmondburgaj I can see that typing file is missing when we install the next version.

There is already open issue for the same #1475. We will prioritize this. Thanks.

**Comment by mattluttrell** [comment]
Also getting this type error on @next. 
Issue #1475 tells us to just use the other project that supports Vue 3. @akki-jat Do you intend to add that type description so your project is compatible with Vue3/Typescript or should we stop using this?

**Comment by mattelen** [comment]
Type definitions now exist in 3.0.0-beta.1. This version can be installed with the `next` tag. I've tested it and it seems to be work well for me, but please let us know if this isn't working for you

**Pull request merged**
