### PR TITLE
Add SCSS to source

### PR DESCRIPTION
**Pull request by kosmiq**
So I continued building on #882 and came up with this.

It's mostly done, some colors needs SCSS variables but I did not put any time into that at this moment.

I have added the ability to change the global selector in SCSS, but there is not support in the Vue setup of course. That might need some looking into.

Other than that I made a fork of the latest master, removed the inline CSS and added a subfolder for SCSS with variables and a style.scss.

Please have a look and report back if you find anything broken, missing etc. I have compared the generated CSS with the old one and it seems I managed to get everything right. Might need to double-check some colors though.

Edit:
A big plus with using a global classname setting is that we can avoing clashes with other libs added. I also added the classname var to the keyframe so that it is prefixed.

### CODE REVIEW

**Comment by kosmiq** [comment]
I should add that I see no reason to add the *.scss files to the /dist folder. Most NPM-packages that includes the /src folder points devs to using /src/scss/* of they need to use the SCSS in their pipeline.

**Comment by eFrane** [comment]
As the `src`-Folder is in the package I agree with not copying over the SCSS file(s). However, and this is unrelated to the current problem, I generally vote for small packages and not distributing all source files.

Anyhow, as this is a much newer and cleaner approach to #882, should we close the latter?

**Comment by Hagith** [comment]
Hi, thanks for your hard work. 
Is this going to land someday? 
It would be great to have SCSS variables instead of **a lot** CSS overrides.

**Comment by kosmiq** [comment]
I am no longer using either the library or Vue. So this is abandoned from my end. Feel free to pick up where I left though.

**Pull request closed without merging**
