### PR TITLE
fix for overflow or z-index issues by appending options to body

### PR DESCRIPTION
**Pull request by yasoza**
Adding fix for the overflow issues when vue-multiselect is loaded in popups, ideally, the options menu container should be visible on top of popups and not be clipped within popup boundaries.

Normal Usage: 
:append-to-body="true" 

if vue-multiselector receives  a `appendToBody` prop it will append the options in body.

`appendToBody` prop can be either boolean or object
if its an object it can have two properties `optionsZindex` and `hideScrollLevel`
optionsIndex = it is the z-index of the options list  by default it is 999
hideScrollLevel = UI can look odd when user can scroll parent container and the options are not scrolling with it, it is not necessary the direct parent has the scrollbar. so it hides the scrollbar up to n level of parents. by default its value is 5. so it sets the style of `overflow:hidden` up to 5 parents in tree. really helpful.

Syntax:
:appendToBody="true" // default optionsZindex = 999 , default hideScrollLevel = 5
:appendToBody="{optionsZindex: 999, hideScrollLevel: 5}" // override the optionsZindex and hideScrollLevel
:appendToBody="{optionsZindex: 999, hideScrollLevel: 5, value: true}" // override the optionsZindex and hideScrollLevel, value is not requried to be set to true

if you want to test in your scenario:

`npm install github:shentao/vue-multiselect#361712de0f6599f0ceadd5e39d2726fac256d460`

Refs:
previous Approach: using the [vue-select](https://github.com/sagalbot/vue-select) appendToBody directive to solve this problem.
Also used this bro's code:  https://github.com/shentao/vue-multiselect/issues/723#issuecomment-660342650

### CODE REVIEW

**Review by yasoza — COMMENTED** [review]
This is old approach of this fix, use the code in previous commits if you want to use it as a workaround to your current version

Usage
v-append-to-body // default optionsZindex = 999 , default hideScrollLevel = 5
v-append-to-body="true" // default optionsZindex = 999 , default hideScrollLevel = 5
v-append-to-body="{optionsZindex: 999, hideScrollLevel: 5}" // override the optionsZindex and hideScrollLevel
v-append-to-body="{optionsZindex: 999, hideScrollLevel: 5, value: true}" // override the optionsZindex and hideScrollLevel, value is not requried to be set true

hideScrollLevel // remove overflow scroll and set it to overflow hidden up to n parents (useful for scrollable parents)
optionsZIndex  // set zindex of options (useful for popups)

Hi, let me know what I need to do next. 
I think I would be writing tests or something or updating the documentation.

**Review by yasoza — COMMENTED** [review]
changed the approach of adding a directive to adding a prop

**Review by yasoza — COMMENTED** [review]
fixed a bug in optionsZIndex prop. all the cases coverd. working smooth.

**Comment by Duncank** [comment]
There is a typo in the name of the beforeDestroy listener.

**Comment by yasoza** [comment]
@Duncank  fixed.

**Comment by DGollings** [comment]
Thanks for this, solves an issue I had 'escaping' a virtual scroller box. Think I found a small bug though:

"[Vue warn]: Error in beforeDestroy hook: "NotFoundError: Node.removeChild: The node to be removed is not a child of this node""

I use multiselect in a v-if multiselect / else 'standard input' (easy way to get a more consistent look&feel in view vs edit mode)

removing the v-else fixes it, so I think its just a race condition, maybe check whether node still exists just before destroying?

**Comment by yasoza** [comment]
@DGollings  Thanks for testing this out. turns out we don't need before destroy hook for what I was trying to achieve, it was the default behaviour. that's why it worked with no error when there was a typo in beforedestroy hook's name. it is fixed. please check again.

**Comment by DGollings** [comment]
appears to have fixeed it, thanks

**Comment by SqrtMinusOne** [comment]
Thanks, that would be nice to merge that into master

**Comment by amiranagram** [comment]
When can we expect a release?

**Comment by DM2489** [comment]
+1, this needs merging!

**Comment by nlaitan** [comment]
+1 when an user opens intentionally an select box, he always wants to see first on foreground. This option makes easy the z-index troubleshooting

**Comment by AndrianStoikov** [comment]
@shentao Can we have this merged? We have a ton of problems on production because of that

**Comment by yasoza** [comment]
Use this directive instead, looks like maintainers ghosted this. 
                
        //  add this to multiselect component ->     :v-append-to-body="true"
        //  make this vue directive globally
        Vue.directive("append-to-body", {
            inserted (el, bindings, { context, child }) {
                let hideScrollLevel = 10 // remove overflow scroll and set it to overflow hidden up to 5 parents by default (useful for scrollable parents)
                let optionsZIndex = 999 // set zindex of options to 999 by default (useful for popups)
                /* usage:
                 *  1. => v-append-to-body // default optionsZindex = 999 , default hideScrollLevel = 5
                 *  2. => v-append-to-body="true" // default optionsZindex = 999 , default hideScrollLevel = 5
                 *  3. => v-append-to-body="{optionsZindex: 999, hideScrollLevel: 5}" // override the optionsZindex and hideScrollLevel
                 *  4. => v-append-to-body="{optionsZindex: 999, hideScrollLevel: 5, value: true}" // override the optionsZindex and hideScrollLevel, value is not requried to be set true
                 */
                function isScrollable(element) { 
                    return element.scrollHeight > element.clientHeight;
                }
                let overflowStates = []
                if (bindings.value === false) {
                  return false
                } else if (typeof bindings.value === 'object') {
                  if (bindings.value.value === false) {
                    return false
                  }
                  hideScrollLevel = bindings.value.hideScrollLevel || hideScrollLevel
                  optionsZIndex = bindings.value.optionsZIndex || optionsZIndex
                }
                function setSizeAndPosition(){
                    context.$children.map(chld => {
                        const optionsRef = chld.$refs.list
  
                        let tempIndex = Number(hideScrollLevel)
              
                        let parentNode = el.parentNode
                        while (tempIndex) {
                          overflowStates[tempIndex] = parentNode.style.overflow
                          if(isScrollable(parentNode)){
                              parentNode.classList.add("drop-overflow")
                              parentNode.style.overflow = 'hidden'
                          }                       
                          parentNode = parentNode.parentNode
                          tempIndex -= 1
                        }
                        if (optionsRef) {
                          const { top, left, width, height } = el.getBoundingClientRect()
                          let scrollX = window.scrollX || window.pageXOffset
                          let scrollY = window.scrollY || window.pageYOffset
                          let totalTop = scrollY + top + height;
                          let styleAttrib = `position:absolute;
                          width:${width}px;
                          left:${scrollX + left}px;
                          top:${totalTop}px;
                          z-index:${optionsZIndex};`
                          let isInTable = document.querySelector('.table-dialouge-popup-container .wrapper') !== null
                          const myBox = document.getElementById('my-box');
                          const footerHeight = document.getElementsByClassName('js-footer') ? document.getElementsByClassName('js-footer')[0].clientHeight : 0;
                          const completeHeight = document.getElementsByTagName('body') ? document.getElementsByTagName('body')[0].offsetHeight : 0;
                          if(myBox && !isInTable)
                            {
                                const availableHeight = completeHeight - totalTop - footerHeight,
                                    maxHeightInPixel = Vue.prototype.convertRemToPixels(15);
                                if (availableHeight < maxHeightInPixel)
                                {
                                    styleAttrib = styleAttrib.concat(`max-height: ${availableHeight}px;`)
                                }
                                else
                                {
                                    styleAttrib = styleAttrib.concat(`max-height: ${maxHeightInPixel}px;`)
                                }
                                
                            }
                          optionsRef.setAttribute(
                              'style',styleAttrib
                          )
                          const optionsTestId = get(bindings, 'value.testId', '')
                          if (optionsTestId) {
                                optionsRef.setAttribute('test-id', optionsTestId)
                          }
                          document.body.appendChild(optionsRef)
                          el._optionsRef = optionsRef
                        }
                      })
                  }
                child.$watch('isOpen', isOpen => {
                  if (isOpen) {
                      setSizeAndPosition();
                      window.addEventListener('resize', setSizeAndPosition);
                  } else {
                    let parentNode = el.parentNode
                    let tempIndex = Number(hideScrollLevel)
                    while (tempIndex) {
                      parentNode.style.overflow = overflowStates[tempIndex]
                      parentNode.classList.remove("drop-overflow")
                      parentNode = parentNode.parentNode
                      tempIndex -= 1
                    }
                    window.removeEventListener('resize', setSizeAndPosition);
                  }
                })
              },
            
              unbind (el, bindings, { context }) {
                if (el._optionsRef) {
                  document.body.removeChild(el._optionsRef)
                }
              }
        })

**Comment by amiranagram** [comment]
That's a shame I really liked this package.

**Comment by eybarta** [comment]
So this library isn't being maintained?

**Comment by eybarta** [comment]
For anyone still having this issue >> 
(I tried the directive ^^ and didn't work for me)

I used the CSS position / overflow trick to overcome the z-index issue inside a scrolled div with multiple multiselects:
This is the code I used to solve this (only relevant props displayed) >>
Make sure only the wrapping ".overflowed" element is positioned (position:relative)

**TEMPLATE**
```
<div
                        ref="ddOverflow"
                        class="overflowed"
                    >
                        <div
                            v-for="(options, i) in dimensionsOptions"
                            :key="options[0].value"
                        >
                            <multiselect
                                v-model="selectedDimensions[i]"
                                :id="`dim-${i}`"
                                @open="ddOpenHandler"
                            ></multiselect>
                        </div>
                    </div>
```

**METHOD**
```
ddOpenHandler(id) {
        const wrap = this.$refs.ddOverflow
        const dd = document.getElementById(id).closest('.multiselect')
        const list = dd.querySelector('.multiselect__content-wrapper')
        this.$nextTick(function() {
            const ddTop = dd.offsetTop
            list.style.top = `${ddTop + dd.offsetHeight - wrap.scrollTop}px`
            list.style.width = `${dd.offsetWidth}px`
        })
    }
```

Good luck!

**Pull request closed without merging**
